Animal tracking point distances
cos301-2019-se/Wildlife-Drones-and-Flight-Plans pull request #25
Opened 2019-05-19 09:18 UTC by EvansMatthew97

2019-05-19 11:18 UTC, BCybercell approved these changes

2019-05-19 11:30 UTC, ASLouw requested changes

2019-05-19 11:30 UTC, ASLouw commented on server/src/services/csv-reader.service.ts
> +}
Missing new line at end of the file.

2019-05-19 11:30 UTC, ASLouw commented on server/src/providers/srtm.service.ts
> +}
Missing new line.

2019-05-19 11:30 UTC, ASLouw commented on server/src/libraries/multi-promise.ts
> +}
Missing new line, add new line for consistency.

2019-05-21 18:33 UTC, BCybercell approved these changes

2019-05-22 05:57 UTC, ASLouw approved these changes

2019-05-22 05:58 UTC, merged