added reserve configuration table and functionality
cos301-2019-se/Wildlife-Drones-and-Flight-Plans pull request #51
Opened 2019-06-10 17:51 UTC by ASLouw

currently cell size is fixed to 1 km

2019-06-21 11:14 UTC, EvansMatthew97 requested changes
I think that the configuration implementation could be better achieved if you use a key-value table, rather than assigning the configuration keys to column names.

So for instance the table could be

```
name        | value
-----------------------------------
reserveName | "Kruger National Park"
cellSize    | 0.4
```

All name fields are strings, as are values. The values would be JSON.


This would mean we can add any new values to the config without having to redefine the database structure.

2019-06-21 11:14 UTC, EvansMatthew97 commented on server/src/entity/reserve-configuration.entity.ts
> +import { Entity, PrimaryColumn ,Column } from 'typeorm';
Can you fix the comma here?

2019-06-21 11:14 UTC, EvansMatthew97 commented on server/src/entity/reserve-configuration.entity.ts
> +  @Column("int")
Use single quotes

2019-06-21 11:14 UTC, EvansMatthew97 commented on server/src/services/map-updater.service.ts
> +import { ReserveConfiguration } from '../entity/reserve-configuration.entity'
Missing semicolon

2019-06-24 14:38 UTC, ASLouw commented on server/src/entity/reserve-configuration.entity.ts
> +import { Entity, PrimaryColumn ,Column } from 'typeorm';
Will do

2019-06-24 14:38 UTC, ASLouw commented on server/src/entity/reserve-configuration.entity.ts
> +  @Column("int")
Right forgot about the standard

2019-06-24 14:38 UTC, ASLouw commented on server/src/services/map-updater.service.ts
> +import { ReserveConfiguration } from '../entity/reserve-configuration.entity'
Will fix

2019-07-02 11:47 UTC, Viidas96 reviewed
not sure about the functionality

2019-07-02 12:26 UTC, EvansMatthew97 approved these changes

2019-07-02 12:38 UTC, merged